apiVersion: batch/v1
kind: Job
metadata:
  name: cqlchaos
spec:
  template:
    spec:
      containers:
      - name: cqlchaos
        image: ryansvihla/cqlchaos:latest
        imagePullPolicy: Always
        command: ["./cqlchaos",  "-hosts=dse-cluster-datastax-dse-0.dse-cluster-datastax-dse" , "-scenario=single-part", "-rf=2"]
      restartPolicy: Never
  backoffLimit: 4
